version: '3.4'
services:
###################################################################
  dominos.services.dbwrite:
    image: ${DOCKER_REGISTRY-}dominosservicesdbwrite
    build:
      context: .
      dockerfile: Dominos.Services.DbWrite/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5010:80"   
    depends_on:
      - rabbitmq
      - sqlserver
###################################################################
  dominos.services.textwrite:
    image: ${DOCKER_REGISTRY-}dominosservicestextwrite
    build:
      context: .
      dockerfile: Dominos.Services.TextWrite/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5020:80"  
    depends_on:
      - rabbitmq

###################################################################
  dominos.services.apigateway:
    image: ${DOCKER_REGISTRY-}dominosapigateway
    build:
      context: .
      dockerfile: Dominos.ApiGateway/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"   
    depends_on:
      - rabbitmq

###################################################################
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "my-rabbit"
    container_name: myrabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    labels:
      NAME: "rabbitmq"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 123456
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 30s
        timeout: 10s
        retries: 5
###################################################################
  sqlserver:
    container_name: "sqlserver"
    image: microsoft/mssql-server-linux:2017-CU8
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
      - SA_PASSWORD=<YourStrong!Passw0rd>
      - MSSQL_DB=DominosDb
    ports:
      - "1433:1433"
###################################################################
